// Package web provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package web

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	// Message Сообщение об ошибке
	Message string `json:"message,omitempty"`
}

// GameInfo defines model for GameInfo.
type GameInfo struct {
	// Id Идентификатор игры
	Id *int `json:"id,omitempty"`

	// Name Название игры
	Name *string `json:"name,omitempty"`
}

// GameState defines model for GameState.
type GameState struct {
	// Field Матрица, описывающая состояние игрового поля
	Field *[][]bool `json:"field,omitempty"`

	// HighScore Максимальное количество очков
	HighScore *int `json:"high_score,omitempty"`

	// Level Поле доп. информации
	Level *int `json:"level,omitempty"`

	// Next Поле доп. информации
	Next *[][]bool `json:"next,omitempty"`

	// Pause Поле доп. информации
	Pause *bool `json:"pause,omitempty"`

	// Score Текущее количество очков
	Score *int `json:"score,omitempty"`

	// Speed Поле доп. информации
	Speed *int `json:"speed,omitempty"`
}

// GamesList defines model for GamesList.
type GamesList struct {
	// Games Список игр
	Games *[]GameInfo `json:"games,omitempty"`
}

// UserAction defines model for UserAction.
type UserAction struct {
	// ActionId Идентификатор действия
	ActionId *int `json:"action_id,omitempty"`

	// Hold Флаг, отвечающий за зажатие кнопки
	Hold *bool `json:"hold,omitempty"`
}

// PostActionsJSONRequestBody defines body for PostActions for application/json ContentType.
type PostActionsJSONRequestBody = UserAction
